### ISSUE TITLE
Multi attribute weapons must have at least 1 attribute point

### ISSUE THREAD

**Issue by GuzziBlues** [Misterguruman/new-world-damage-simulator#3]
Equipping a weapon with multiple attributes wastes 1 point in final calculations. Consider the following.

``` Json
    "base_stats": {
        "Strength": 108,
        "Dexterity": 22,
        "Intelligence": 5,
        "Focus": 11,
        "Constitution": 49
    },
    "character": {
        "level": 45,
        "primary_weapon": "Great Axe",
        "primary_base_dmg": 158,
        "secondary_weapon": "Hatchet",
        "secondary_base_dmg": 128
    },
    "app_settings": {
        "desired_ap_to_constitution": 0
    }
```

Results in

![image](https://user-images.githubusercontent.com/92407103/137042476-29e73a95-e91f-4bf0-8411-d8f331b7b568.png)

When it should be

![image](https://user-images.githubusercontent.com/92407103/137042644-0eaf71c2-1c63-4b02-bd15-d2b2e537a91a.png)

Solution
Change line 159, range should start at 0.
![image](https://user-images.githubusercontent.com/92407103/137042730-7e5d7808-ba1d-4d70-82fb-575d27008a8b.png)

**Comment by Misterguruman** [comment]
You are on a roll today my man, I'm on it

**Comment by Misterguruman** [comment]
Closing, resolved with latest commit
